### ISSUE TITLE
Python formatter workflow has import errors

### ISSUE THREAD

**Issue by quisquous** [quisquous/cactbot#4321]
https://github.com/quisquous/cactbot/runs/6137579415?check_suite_focus=true

```
Run black **/*.py --line-length 100 --check --diff
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.[7](https://github.com/quisquous/cactbot/runs/6137579415?check_suite_focus=true#step:7:7).12/x64/bin/black", line [8](https://github.com/quisquous/cactbot/runs/6137579415?check_suite_focus=true#step:7:8), in <module>
    sys.exit(patched_main())
  File "/opt/hostedtoolcache/Python/3.7.[12](https://github.com/quisquous/cactbot/runs/6137579415?check_suite_focus=true#step:7:12)/x64/lib/python3.7/site-packages/black.py", line 4[13](https://github.com/quisquous/cactbot/runs/6137579415?check_suite_focus=true#step:7:13)4, in patched_main
    patch_click()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/click/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by Bing-su** [comment]
https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click

it says `This has been fixed by Black 22.3.0. Versions before that won't work with click 8.1.0.`

```sh
Collecting black==19.10b0
  Downloading black-19.10b0-py36-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.5/97.5 KB 14.1 MB/s eta 0:00:00
...
Collecting click>=6.5
  Downloading click-8.1.2-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 21.0 MB/s eta 0:00:00
```

cactbot still use black==19.10b0... How about using the latest version of the black?
